"""add email_verified and status to users

Revision ID: 558df5e7b2ed
Revises: 36822c17158e
Create Date: 2026-09-15 12:15:17.481937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '558df5e7b2ed'
down_revision: Union[str, Sequence[str], None] = '36822c17158e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default fills existing rows during the ALTER (satisfies NOT NULL).
    op.add_column(
        'users',
        sa.Column(
            'email_verified', sa.Boolean(),
            nullable=False, server_default=sa.text('false'),
        ),
    )
    # Create the enum TYPE first — it doesn't exist yet (this table already
    # existed, so unlike role/sex the status enum was never created).
    status_enum = sa.Enum('pending', 'approved', 'rejected', name='status')
    status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'users',
        sa.Column(
            'status', status_enum,
            nullable=False, server_default='pending',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('users', 'email_verified')
    sa.Enum(name='status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
