"""add patient names

Revision ID: 6587dd68e8bf
Revises: 558df5e7b2ed
Create Date: 2026-09-17 22:06:35.347735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6587dd68e8bf'
down_revision: Union[str, Sequence[str], None] = '558df5e7b2ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default fills the existing patient row during the ALTER.
    op.add_column(
        'patients',
        sa.Column('first_name', sa.String(length=100),
                  nullable=False, server_default='Unknown'),
    )
    op.add_column(
        'patients',
        sa.Column('last_name', sa.String(length=100),
                  nullable=False, server_default='Unknown'),
    )
    op.create_index(op.f('ix_patients_last_name'), 'patients', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_last_name'), table_name='patients')
    op.drop_column('patients', 'last_name')
    op.drop_column('patients', 'first_name')
    # ### end Alembic commands ###
